//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assign1._1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Restaurant
    {
        public int Id { get; set; }
        public string Name { get; set; }
        [Required]
        [Phone (ErrorMessage ="Please input vaild phone number")]
        public string Telephone_No { get; set; }
        public string Address { get; set; }
        public double Latitude { get; set; }
        public double Longitude { get; set; }
        public int BookingId { get; set; }
    
        public virtual Booking Booking { get; set; }
    }
}
